name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-02-06
          override: true
          components: rustfmt, clippy, rust-src

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Install solc
        run: cargo install svm-rs && svm install 0.8.26 && svm use 0.8.26 && solc --version

      - name: Run test
        run: cargo test --workspace --all-features --all-targets -- --nocapture

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings
